### ISSUE TITLE
Connecting to OpenAI for Story Generation

### ISSUE THREAD

**Issue by AVTpepper** [AVTpepper/halloween-hackathon#21]
EPIC #14 
As a **developer** I want to **connect to OpenAI ** so that **I can automatically generate short spooky stories for the user**.

## Acceptance criteria
  * Acceptance criteria 1: The site successfully fetches a short story from OpenAI without errors.
  * Acceptance criteria 2: The generated story reflects a spooky theme appropriate for the site's theme.
  * Acceptance criteria 3: The connection is secure and user data is not at risk.

 ## Tasks
 - [x]  Implement OpenAI API connection in the backend.
 - [x] Test API response with sample requests.
 - [x] Handle potential API errors gracefully in the frontend.

**Comment by sbojorge** [comment]
All tasks completed. This issue can be closed.
