### ISSUE TITLE
EPIC: Deployment

### ISSUE THREAD

**Issue by sbojorge** [AVTpepper/halloween-hackathon#31]
This epic covers the deployment process on GitHub.

As a reminder, these are the steps for deploying:

1. In the GitHub repository, navigate to the "Settings" tab;
2. Click on "Pages" from the left hand menu;
3. In the "Branch" section, from the drop-down menu, select "main" and click on Save;
4. Refresh the page manually. The link to the deployed website should be available.

After deployment, just click on "Close issue".

**Comment by AVTpepper** [comment]
deployed.
